### ISSUE TITLE
ModuleNotFoundError: No module named 'crontab'  even if requirements satisfied

### ISSUE THREAD

**Issue by Satendrapatel980** [hisxo/gitGraber#49]
###  `pip3 install -r requirements.txt`
_Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests==2.31.0 in /home/kali/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: argcomplete==3.2.1 in /home/kali/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: python_crontab==2.3.9 in /home/kali/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.3.9)
Requirement already satisfied: termcolor==1.1.0 in /home/kali/.local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/kali/.local/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/kali/.local/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/kali/.local/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 1)) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/kali/.local/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 1)) (2022.6.15)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from python_crontab==2.3.9->-r requirements.txt (line 3)) (2.8.2)_
                                                                                           
```
 ┌──(kali㉿kali)-[~/Desktop/tools/gitGraber]
└─$ sudo python3 gitGraber.py -k wordlists/keywords.txt -q "etsy.com" 
```
Traceback (most recent call last):
  File "/home/kali/Desktop/tools/gitGraber/gitGraber.py", line 21, in <module>
    from crontab import CronTab
ModuleNotFoundError: No module named 'crontab'

**Comment by anjan123427** [comment]
Traceback (most recent call last):
  File "/home/kali/gitGraber/gitGraber.py", line 21, in <module>
    from crontab import CronTab
ModuleNotFoundError: No module named 'crontab'

same issue

**Comment by anjan123427** [comment]
Brother Try this  **pip install python-crontab**
